[COREV] Add CI workflow file corev-llvm-tests.yml.
openhwgroup/corev-llvm-project pull request #23
Opened 2022-12-26 08:25 UTC by xingmingjie

2023-02-24 03:10 UTC, xingmingjie commented
The PR should be updated later.

2023-02-24 08:40 UTC, jeremybennett requested changes

2023-02-24 08:40 UTC, jeremybennett commented on .github/workflows/corev-llvm-tests.yml
> +    # if: github.repository_owner == 'llvm'
Uncomment this and restrict only to organization `openhwgroup`

2023-03-03 08:35 UTC, jeremybennett commented
Suggest we should disable Windows for the time being, so we can merge this.

2023-03-03 08:47 UTC, simonpcook commented
These jobs all take a long time because caches are cold, is it possible to [increase timeouts](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) instead?

2023-03-06 07:46 UTC, xingmingjie commented
> These jobs all take a long time because caches are cold, is it possible to [increase timeouts](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes) instead?

See https://github.com/github/docs/issues/7984. The jobs.<job_id>.timeout-minutes description is misleading, we can't set a value larger than 360 when using GitHub hosted runners. So I just disabled windows for the time being.

2023-03-06 09:27 UTC, jeremybennett commented on .github/workflows/corev-llvm-tests.yml
> +    # if: github.repository_owner == 'llvm'
Thanks for updating this.

2023-03-06 09:27 UTC, jeremybennett approved these changes
This is now good to merge.

2023-03-07 10:28 UTC, jeremybennett commented
@xingmingjie I am going to merge this, even though the tests failed, because the failure was in one of the tests, not in the CI infrastructure itself.

2023-03-07 10:28 UTC, merged