[RISCV] Update immediate branching extension
openhwgroup/corev-llvm-project pull request #55
Opened 2023-04-24 12:51 UTC by melonedo

Spec: https://github.com/openhwgroup/cv32e40p/blob/62bec66b36182215e18c9cf10f723567e23878e9/docs/source/instruction_set_extensions.rst#immediate-branching-operations

Update the format and the command line flag of the immediate branching extension.

2023-04-28 07:41 UTC, jeremybennett requested changes
One small change needed, then this can be merged.

2023-04-28 07:41 UTC, jeremybennett commented on llvm/test/CodeGen/RISCV/corev/bi.ll
> +; RUN: llc -O0 -mtriple=riscv32 -mattr=+m -mattr=+xcvbi -verify-machineinstrs < %s \
We don't need the `+mattr=+m` to turn on the RISC-V mutliply extension.

2023-05-04 14:32 UTC, melonedo commented on llvm/test/CodeGen/RISCV/corev/bi.ll
> +; RUN: llc -O0 -mtriple=riscv32 -mattr=+m -mattr=+xcvbi -verify-machineinstrs < %s \
Fixed

2023-05-05 07:51 UTC, jeremybennett commented
This is now good to merge.

2023-05-05 07:51 UTC, merged